import { Router } from 'express';
import { authenticate, AuthRequest } from '../middleware/auth';
import { supabase } from '../config/supabase';
import { wouldExceedMembers, memberLimit, type SubscriptionRow } from '../lib/planLimits';

export const invitesRouter = Router();
invitesRouter.use(authenticate);

const ALLOWED_ROLES = ['admin', 'manager', 'office', 'field', 'viewer'] as const;
type InviteRole = typeof ALLOWED_ROLES[number];

// Verify the caller is an owner or admin of the given business.
async function assertAdmin(userId: string, businessId: string): Promise<boolean> {
  const { data } = await supabase
    .from('business_members')
    .select('role')
    .eq('user_id', userId)
    .eq('business_id', businessId)
    .maybeSingle();
  return data?.role === 'owner' || data?.role === 'admin';
}

/**
 * POST /api/v1/invites
 * Body: { business_id, email, role }
 * Creates a business_invites row and sends an invite email via Supabase Auth's
 * built-in inviteUserByEmail (no extra email provider needed). Returns the
 * accept URL so the inviter can also copy/share it manually.
 */
invitesRouter.post('/', async (req: AuthRequest, res) => {
  const userId = req.user?.id;
  if (!userId) return res.status(401).json({ success: false, message: 'Unauthenticated' });

  const { business_id, email, role } = req.body ?? {};
  if (!business_id || !email || !role) {
    return res.status(400).json({ success: false, message: 'business_id, email, role required' });
  }
  // Built-in invitable roles, or a custom role defined by this business
  // (business_roles with is_system=false, migration 179). The DB trigger
  // re-validates on insert, this just gives a clean 400.
  if (!ALLOWED_ROLES.includes(role as InviteRole)) {
    const { data: customRole } = await supabase
      .from('business_roles')
      .select('key')
      .eq('business_id', business_id)
      .eq('key', role)
      .eq('is_system', false)
      .maybeSingle();
    if (!customRole) {
      return res.status(400).json({ success: false, message: 'invalid role' });
    }
  }

  const normalizedEmail = String(email).trim().toLowerCase();
  if (normalizedEmail === req.user?.email?.toLowerCase()) {
    return res.status(400).json({ success: false, code: 'invite_self' });
  }

  if (!(await assertAdmin(userId, business_id))) {
    return res.status(403).json({ success: false, message: 'forbidden' });
  }

  // If they're already a member, reject early.
  const { data: existingMember } = await supabase
    .from('business_members')
    .select('id, user_id, role, users:user_id(email)')
    .eq('business_id', business_id);
  const alreadyMember = (existingMember ?? []).some(
    (m: any) => (m.users?.email ?? '').toLowerCase() === normalizedEmail,
  );
  if (alreadyMember) {
    return res.status(409).json({ success: false, code: 'already_member' });
  }

  // If there's already a pending invite for this email + business, reject.
  const { data: pending } = await supabase
    .from('business_invites')
    .select('id')
    .eq('business_id', business_id)
    .ilike('email', normalizedEmail)
    .is('accepted_at', null)
    .gt('expires_at', new Date().toISOString())
    .maybeSingle();
  if (pending) {
    return res.status(409).json({ success: false, code: 'already_invited' });
  }

  // Seat cap. Counts current members + every unaccepted, unexpired invite —
  // a pending invite is a seat already spoken for, or you could queue a
  // hundred of them under a 2-seat plan. Nobody already on the team is ever
  // removed; the cap only refuses to add someone new.
  const [{ data: bizRow }, { count: pendingCount }] = await Promise.all([
    supabase
      .from('businesses')
      .select('plan, subscription_status, trial_ends_at')
      .eq('id', business_id)
      .maybeSingle(),
    supabase
      .from('business_invites')
      .select('id', { count: 'exact', head: true })
      .eq('business_id', business_id)
      .is('accepted_at', null)
      .gt('expires_at', new Date().toISOString()),
  ]);
  if (bizRow) {
    const sub = bizRow as SubscriptionRow;
    const used = (existingMember ?? []).length + (pendingCount ?? 0);
    if (wouldExceedMembers(sub, used)) {
      return res.status(409).json({
        success: false,
        code: 'seat_limit',
        limit: memberLimit(sub),
        used,
      });
    }
  }

  // Create the invite row. Token is auto-generated by the DB default.
  const { data: invite, error: insertErr } = await supabase
    .from('business_invites')
    .insert({
      business_id,
      email: normalizedEmail,
      role,
      invited_by: userId,
    })
    .select('id, token, business_id, role, email, expires_at')
    .single();
  if (insertErr || !invite) {
    return res.status(500).json({ success: false, message: insertErr?.message ?? 'insert_failed' });
  }

  const frontendUrl = process.env.FRONTEND_URL ?? 'http://localhost:3000';
  const acceptUrl = `${frontendUrl.replace(/\/$/, '')}/invitacion/${invite.token}`;

  // Send invitation email via Supabase Auth's built-in inviter. This creates
  // a pending auth user if none exists yet, and emails them a magic link
  // redirecting to our accept URL. Failures are non-fatal — the invite row
  // exists either way, and the admin can copy the link manually.
  let emailSent = false;
  try {
    const { error: emailErr } = await supabase.auth.admin.inviteUserByEmail(normalizedEmail, {
      redirectTo: acceptUrl,
      data: { invite_token: invite.token, business_id, role },
    });
    if (!emailErr) {
      emailSent = true;
    } else {
      // eslint-disable-next-line no-console
      console.warn('[invites] inviteUserByEmail failed', emailErr.message);
    }
  } catch (e) {
    // eslint-disable-next-line no-console
    console.warn('[invites] inviteUserByEmail threw', e);
  }

  // Audit log
  await supabase.from('audit_log').insert({
    business_id,
    user_id: userId,
    action: 'invite.sent',
    entity_type: 'invite',
    entity_id: invite.id,
    details: { email: normalizedEmail, role, email_sent: emailSent },
  });

  return res.json({
    success: true,
    data: {
      id: invite.id,
      email: invite.email,
      role: invite.role,
      acceptUrl,
      expiresAt: invite.expires_at,
      emailSent,
    },
  });
});

/**
 * DELETE /api/v1/invites/:id
 * Revoke a pending invite. Admin-only.
 */
invitesRouter.delete('/:id', async (req: AuthRequest, res) => {
  const userId = req.user?.id;
  if (!userId) return res.status(401).json({ success: false, message: 'Unauthenticated' });

  const { data: invite } = await supabase
    .from('business_invites')
    .select('id, business_id, email, role')
    .eq('id', req.params.id)
    .maybeSingle();
  if (!invite) return res.status(404).json({ success: false, message: 'not_found' });

  if (!(await assertAdmin(userId, invite.business_id))) {
    return res.status(403).json({ success: false, message: 'forbidden' });
  }

  await supabase.from('business_invites').delete().eq('id', invite.id);

  await supabase.from('audit_log').insert({
    business_id: invite.business_id,
    user_id: userId,
    action: 'invite.revoked',
    entity_type: 'invite',
    entity_id: invite.id,
    details: { email: invite.email, role: invite.role },
  });

  return res.json({ success: true });
});

/**
 * POST /api/v1/invites/:id/resend
 * Resend the email for a pending invite (does not change the token).
 */
invitesRouter.post('/:id/resend', async (req: AuthRequest, res) => {
  const userId = req.user?.id;
  if (!userId) return res.status(401).json({ success: false, message: 'Unauthenticated' });

  const { data: invite } = await supabase
    .from('business_invites')
    .select('id, business_id, email, token, expires_at, accepted_at')
    .eq('id', req.params.id)
    .maybeSingle();
  if (!invite) return res.status(404).json({ success: false, message: 'not_found' });
  if (invite.accepted_at) return res.status(400).json({ success: false, message: 'already_accepted' });

  if (!(await assertAdmin(userId, invite.business_id))) {
    return res.status(403).json({ success: false, message: 'forbidden' });
  }

  const frontendUrl = process.env.FRONTEND_URL ?? 'http://localhost:3000';
  const acceptUrl = `${frontendUrl.replace(/\/$/, '')}/invitacion/${invite.token}`;

  let emailSent = false;
  try {
    const { error } = await supabase.auth.admin.inviteUserByEmail(invite.email, {
      redirectTo: acceptUrl,
      data: { invite_token: invite.token },
    });
    emailSent = !error;
  } catch {
    /* swallow */
  }

  return res.json({ success: true, data: { acceptUrl, emailSent } });
});

/**
 * GET /api/v1/invites?business_id=...
 * List pending invites for a business. Admin-only.
 */
invitesRouter.get('/', async (req: AuthRequest, res) => {
  const userId = req.user?.id;
  if (!userId) return res.status(401).json({ success: false, message: 'Unauthenticated' });

  const businessId = req.query.business_id as string | undefined;
  if (!businessId) return res.status(400).json({ success: false, message: 'business_id required' });

  if (!(await assertAdmin(userId, businessId))) {
    return res.status(403).json({ success: false, message: 'forbidden' });
  }

  const { data } = await supabase
    .from('business_invites')
    .select('id, email, role, token, expires_at, accepted_at, created_at')
    .eq('business_id', businessId)
    .is('accepted_at', null)
    .order('created_at', { ascending: false });

  const frontendUrl = process.env.FRONTEND_URL ?? 'http://localhost:3000';
  const items = (data ?? []).map(i => ({
    ...i,
    acceptUrl: `${frontendUrl.replace(/\/$/, '')}/invitacion/${i.token}`,
  }));

  return res.json({ success: true, data: items });
});
